apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  interval: 168h
  path: ./apps/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
